### ISSUE TITLE
Wifi turns off itself after few seconds

### ISSUE THREAD

**Issue by StefanSchwartze** [tessel/t2-cli#523] opened 2016-01-14 14:39 UTC
When successful connected to a wifi network, almost immediately itself turns off the wifi module. After a time, it turns on and off again. When connected with ssh, it logs the following:
```
wifi
root@HAL:/# [  423.320000] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  424.890000] wlan0: authenticate with 18:83:bf:8b:9d:01
[  424.930000] wlan0: send auth to 18:83:bf:8b:9d:01 (try 1/3)
[  424.930000] wlan0: authenticated
[  424.950000] wlan0: associate with 18:83:bf:8b:9d:01 (try 1/3)
[  424.950000] wlan0: RX AssocResp from 18:83:bf:8b:9d:01 (capab=0x411 status=0 aid=1)
[  424.960000] wlan0: associated
[  424.970000] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[  434.970000] wlan0: deauthenticating from 18:83:bf:8b:9d:01 by local choice (Reason: 3=DEAUTH_LEAVING)
```
[log.txt](https://github.com/tessel/t2-cli/files/90522/log.txt)

**Comment by johnnyman727** [comment] 2016-01-27 01:58
@StefanSchwartze did you confirm that this was an issue with your router?

**Comment by StefanSchwartze** [comment] 2016-02-09 14:31
Oh, I'm sorry I didn't answer yet. I've also tried it with the same WPA2 security on another router, but I've got the same error. Connecting with WPA works fine.

**Comment by rwaldron** [comment] 2016-04-02 17:30
@HipsterBrown please investigate

**Comment by johnnyman727** [comment] 2016-04-02 19:21
My two cents is that this is likely an issue with the router. @HipsterBrown is you get around to this, I'd be interested to hear your testing strategy.

**Comment by HipsterBrown** [comment] 2016-04-03 17:46
I'll look into this again today.

**Comment by johnnyman727** [comment] 2016-08-09 17:58
I'm closing this issue for now because we are unable to reproduce it.

**Closed by johnnyman727** 2016-08-09 17:58 UTC
