### ISSUE TITLE
[unit tests] Flaky tests in access-point.js

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#557] opened 2016-02-10 22:01 UTC
Ever so often I get this output when running the tests locally. Rerunning fixes it.

```text
Running "nodeunit:tests" (nodeunit) task
Testing access-point.jsFFFFFF
>> Tessel.prototype.createAccessPoint - newAccessPoint
>> TypeError: Cannot read property 'mockClose' of undefined
>> at Object.exports.Tessel.prototype.createAccessPoint.tearDown (test/unit/access-point.js:34:16)

>> Tessel.prototype.createAccessPoint - noPasswordNoSecurity
>> TypeError: Cannot read property 'mockClose' of undefined
>> at Object.exports.Tessel.prototype.createAccessPoint.tearDown (test/unit/access-point.js:34:16)

>> Tessel.prototype.createAccessPoint - properCredentials
>> TypeError: Cannot read property 'mockClose' of undefined
>> at Object.exports.Tessel.prototype.createAccessPoint.tearDown (test/unit/access-point.js:34:16)

>> Tessel.prototype.createAccessPoint - passwordNoSecurity
>> TypeError: Cannot read property 'mockClose' of undefined
>> at Object.exports.Tessel.prototype.createAccessPoint.tearDown (test/unit/access-point.js:34:16)

>> Tessel.prototype.enableAccessPoint - turnsOn
>> TypeError: Cannot read property 'mockClose' of undefined
>> at Object.exports.Tessel.prototype.enableAccessPoint.tearDown (test/unit/access-point.js:221:16)

>> Tessel.prototype.disableAccessPoint - turnsOn
>> TypeError: Cannot read property 'mockClose' of undefined
>> at Object.exports.Tessel.prototype.disableAccessPoint.tearDown (test/unit/access-point.js:267:16)
```

**Comment by johnnyman727** [comment] 2016-02-10 22:03
Thanks for reporting this. I've also seen this a bunch of times but didn't record it in our issues.

**Comment by rwaldron** [comment] 2016-04-02 17:30
@HipsterBrown assigning to you. Please investigate and report (either can repro, or cannot)

**Comment by johnnyman727** [comment] 2016-04-02 19:20
From my experience, this has nothing to do with the access point tests. I believe I saw this issue intermittently before we even had the access point feature. It's pretty hard to reproduce (maybe 1 in 100 test runs will hit it).

**Comment by johnnyman727** [comment] 2016-05-20 08:51
I'm still hitting this and, while I don't know the root cause, I think what's happening is a race condition in the `setUp` of the first access point test. Sometimes an error is thrown before it gets to the line where it creates `this.tessel` (which `mockClose` is a property of). After the error is noted by sinon, it calls the `tearDown` function which tries `mockClose` but can't call it because `this.tessel` was never initialized.

A workaround would be to explicitly call `this.tessel.mockClose` after each test or just check that `this.tessel` is defined before calling `this.tessel.mockClose`. Obviously, figuring out the root cause is preferred.

**Comment by johnnyman727** [comment] 2016-07-15 13:09
Another hint! Following my hunch in the above comment, I added a try/catch around the `setUp` of the `access-point.js` test. And then a wild `Error` appeared!
```
Running "nodeunit:tests" (nodeunit) task
Testing access-point.jswould have failed with error [ReferenceError: sinon is not defined]
Fwould have failed with error [ReferenceError: sinon is not defined]
Fwould have failed with error [ReferenceError: sinon is not defined]
Fwould have failed with error [ReferenceError: sinon is not defined]
FFFFFF
>> Tessel.prototype.createAccessPoint - newAccessPoint
>> Error: Expected 20 assertions, 0 ran

>> Tessel.prototype.createAccessPoint - newAccessPoint
>> TypeError: Cannot read property 'mockClose' of undefined
>> at Object.exports.Tessel.prototype.createAccessPoint.tearDown (test/unit/access-point.js:48:16)
...
```

So it looks like the issue happens when `sinon` doesn't get defined before this test is run. `sinon` gets defined in `"test/common/bootstrap.js"` so the mechanism that loads that file seems to have the race condition.

This is consistent with my observation that this issue was occurring before we even had `access-point.js` because it would be thrown in whatever the first test file is (they all use `sinon`).

I'm currently investigating why the order in which test files are loaded isn't deterministic.

**Comment by johnnyman727** [comment] 2016-07-15 14:40
@rwaldron do you think this could be an issue with `grunt` itself? I'm not sure how it loads test files. Maybe it's using async but really needs to be sync?

**Comment by johnnyman727** [comment] 2016-07-15 14:45
I added a console.log to the top of `test/unit/access-point.js` and `test/common/bootstrap.js` and confirmed that occasionally `bootstrap.js` gets loaded *after* `access-point.js`.

**Comment by johnnyman727** [comment] 2016-07-15 15:19
Just following the path of execution:
1. Enters `grunt-nodeunit-unit` task [here](https://github.com/tessel/t2-cli/blob/master/Gruntfile.js#L12)
2. File array gets [passed to `nodeunit`](https://github.com/gruntjs/grunt-contrib-nodeunit/blob/master/tasks/nodeunit.js#L237)
3. `nodeunit` attempts to [fish all source files out independent directories](https://github.com/caolan/nodeunit/blob/master/lib/utils.js#L58) and does so asynchronously. I believe this has the chance of returning files out of order and is the source of the bug.

It also looks like [I wasn't the first person to come to the conclusion](https://github.com/caolan/nodeunit/issues/296).

I'll make a patch and try it out. We don't have a great way to test the race condition but I'll run it like 20 times to make sure (I usually get it within 10 executions of `grunt`).

**Comment by johnnyman727** [comment] 2016-07-15 15:41
We have an interesting predicament with the CLI because of this. [`grunt-contrib-nodeunit`](https://github.com/gruntjs/grunt-contrib-nodeunit) which runs our unit tests depends on [`nodeunit`](https://github.com/caolan/nodeunit).

`nodeunit` has this bad race condition but the fix is easy and I’ve made it. But the maintainer of `nodeunit` has been absent for a couple of years (ie it’s not maintained). I can fork `nodeunit` but I don’t want to also fork the well-maintained `grunt-contrib-nodeunit` and update its reference from official `nodeunit` to my fork. If I did that, it would be difficult to keep getting updates from the official `grunt-contrib-nodeunit`. I also don’t want to update their `nodeunit` reference to my repo because I don’t want to maintain `nodeunit`. What’s a developer to do?

**Comment by johnnyman727** [comment] 2016-07-15 16:25
Another workaround is to just `require('bootstrap')` from all test files...

**Comment by rwaldron** [comment] 2016-07-15 20:03
How is that this is a pressing issue? I've seen errors caused by out-of-order loading only a handful of times across all of the projects that I've used nodeunit—and only the ones where I lump everything into `bootstrap.js`. I've been aware of this (non) issue since forever :P 

For whatever reason, I either missed this original issue being filed or forgot about it. Anyway, I moved all the dep requiring into bootstrap.js in [November](https://github.com/tessel/t2-cli/commit/17765e26dc4b3980c39061e8faee5323789b1146) and it took about 2 1/2-3 months for an issue to surface. 


> Another workaround is to just require('bootstrap') from all test files...

Sure, let's do that.

**Comment by rwaldron** [comment] 2016-07-15 20:19
Ref: https://github.com/tessel/t2-cli/pull/798

**Closed** 2016-07-15 21:53 UTC

**Comment by johnnyman727** [comment] 2016-07-15 22:33
@rwaldron thanks for taking that on. 

It's not pressing as much as incredibly frustrating. For whatever reason, AppVeyer has been hitting this with virtually every PR I make and I've spent a lot of time restarting the tests. I'm glad I can stop worrying about it!
