### ISSUE TITLE
Misleading error message on t2 update for unauthenticated Tessel

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#485] opened 2015-12-11 03:13 UTC
This is what happens when you try to update with an unauthenticated but Wifi connected tessel:

```sh
➜  t2-cli git:(master) t2 update
INFO Looking for your Tessel...
INFO Connected to LOL.
WARN No LAN connection found. USB-only updates do not work yet. Please ensure Tessel is connected to wifi and try again
```

suggestion: add "connected to wifi & authenticated with t2 provision"

**Comment by johnnyman727** [comment] 2015-12-11 03:32
Agreed! Duplicate of https://github.com/tessel/t2-cli/issues/410.

**Closed by johnnyman727** 2015-12-11 03:32 UTC
