### ISSUE TITLE
Configurable IP Address

### ISSUE THREAD

**Issue by huseyinkozan** [tessel/t2-cli#510] opened 2016-01-03 01:43 UTC
Hi,

I have installed t2-vm and created a vm. But, I cannot `t2 list` while I have firewall enabled. I had allowed mdsn port 5353 but not success (#443). I thing, this is the main reason : [node-mdns-js/issues/45] (https://github.com/mdns-js/node-mdns-js/issues/45).

Can we add an option to set IP address of the device, for example; a file in ~/.tessel/vm.ip. If that file exists, the library should skip the discovery phase and use the IP address.

**Comment by johnnyman727** [comment] 2016-01-04 20:29
@huseyinkozan I agree that we need support for Tessels that may not be discoverable with mDNS for one reason or another. 

This is a duplicate of https://github.com/tessel/t2-cli/issues/70 - would you mind continuing the discussion there?

**Closed by johnnyman727** 2016-01-04 20:29 UTC
