### ISSUE TITLE
Wifi appears to work only when I'm not running code

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#758] opened 2016-06-03 09:03 UTC
This is an odd thing. I'm connected to a Wifi network. The yellow light blinks intermittently, and if I run `t2 wifi` I get this positive message:

```
➜  ktest t2 wifi
INFO Looking for your Tessel...
INFO Connected to yayLookItsATessel.
INFO Connected to "WebRebels"
INFO Signal Strength: (35/70)
INFO Bitrate: 7mbps
```

However, I am trying to run the Twitter example. And every time I run it, the yellow light turns off for the duration, the tweet fails to send, the code completes and exits, and then the yellow light comes back.

```
➜  ktest t2 run twitter.js
INFO Looking for your Tessel...
INFO Connected to yayLookItsATessel.
INFO Building project.
INFO Writing project to RAM on yayLookItsATessel (950.272 kB)...
INFO Deployed.
INFO Running twitter.js...
error sending tweet: { [Error: getaddrinfo ENOTFOUND api.twitter.com api.twitter.com:443]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.twitter.com',
  host: 'api.twitter.com',
  port: 443 }
```

I've repeated this 5 times now, and it's very consistent. I also tried running the accelerometer example (where Wifi is not used) and observed the same yellow-light behavior.

Any clues? Is anyone else experiencing this?

**Comment by Frijol** [comment] 2016-06-03 09:08
Ah- I think it's related to https://github.com/tessel/t2-cli/issues/755. I dterm'd in, as in the other issue, and deleted the extra `config wifi-iface` from the bottom of Tessel's `etc/config/wireless`. Then I ran the Twitter example again and it worked perfectly.

We need to figure out why that extra line is being written.

**Comment by johnnyman727** [comment] 2016-06-03 13:28
I found out why the extra `config wifi-iface` is being added to the bottom of the file. [This line is intended to check if an existing `wifi-iface` is set up for a LAN](https://github.com/tessel/t2-cli/blob/9035c89e9ada3de7dd7708ad744e45a48618260b/lib/tessel/access-point.js#L147) and it adds a new one if one wasn't detected. However, based on the default `/etc/config/wireless` file as edited [here](https://github.com/tessel/openwrt-tessel/pull/31/files), there should always be an existing `wifi-iface` for LAN. This detection method is screwy because it checks for the access point SSID as a way of checking to see if the access point exists at all but we, by default, have an access point with no SSID. Therefore, it creates a new `wifi-iface`. This can be fixed by simply checking to see if `uci get iwifi-iface[1]` returns an error.

I have also seen that not explicitly disabling the wifi interface will cause the `ap` to not be found so we should explicitly disable wifi when setting the access point on (and vice versa).

**Comment by Frijol** [comment] 2016-06-04 08:11
Additional point of interest: I had the ap on, and ran `t2 wifi` to find that it was ... connected to itself

```
➜  ktest2 t2 wifi
INFO Looking for your Tessel...
INFO Connected to yayLookItsATessel.
INFO Connected to "Tessel"
INFO IP Address: 192.168.1.101
INFO Signal Strength: (undefined/70)
INFO Bitrate: NaNmbps
```

**Comment by johnnyman727** [comment] 2016-08-09 18:27
It's possible that this was fixed with https://github.com/tessel/t2-cli/pull/761. We need someone to try to reproduce this (which may be difficult because we've only seen it on one network). I'm going to close this for now but we can re-open if it rears it's ugly head once again.

**Closed by johnnyman727** 2016-08-09 18:27 UTC
Labels: bug, Stumbling Block, urgent
