### ISSUE TITLE
Early detection of bootloader mode during update

### ISSUE THREAD

**Issue by scottgonzalez** [tessel/t2-cli#428] opened 2015-11-03 00:50 UTC
During an update, I forgot to put the Tessel into bootloader mode. The update got pretty far along before erroring out because it wasn't in bootloader mode. The update should probably check for the proper mode upfront so it can fail early. Also, after the error, the program didn't quite; I had to send a kill signal to end it.

```
$ t2 update
INFO Looking for your Tessel...
INFO Connected to scott over LAN
INFO New firmware version found...0.0.5
INFO Updating scott to latest version (0.0.5)...
INFO Beginning update download. This could take a couple minutes..
  downloading [====================] 100% 0.0s remaining
INFO Download complete!
INFO Updating OpenWRT (1/2)
INFO Transferring image of size 20.19 MB
INFO Starting OpenWRT update. Please do not remove power from Tessel.
INFO Updating firwmare (2/2)
Unhandled rejection Error: No device found in bootloader mode
    at /Users/scottgonzalez/Projects/t2-cli/lib/usb_connection.js:272:19
    at tryCatcher (/Users/scottgonzalez/Projects/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/scottgonzalez/Projects/t2-cli/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/scottgonzalez/Projects/t2-cli/node_modules/bluebird/js/main/promise.js:70:37)
    at USB.Connection._findBootedDeviceBySerialNumber (/Users/scottgonzalez/Projects/t2-cli/lib/usb_connection.js:256:10)
    at retry [as _onTimeout] (/Users/scottgonzalez/Projects/t2-cli/lib/usb_connection.js:233:19)
    at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by scottgonzalez** [comment] 2015-11-03 00:51
After rebooting in bootloader mode, I get the following output:

```
$ t2 update
INFO Looking for your Tessel...
WARN Detected a Tessel that may be booting.
WARN No Authorized Tessels Found.
```

Seems like there's no path forward.

**Comment by rwaldron** [comment] 2015-11-03 15:06
You don't need to put the T2 into bootloader mode when using `t2 update`, but the board needs to be connected via both USB and LAN—can you confirm?

**Comment by scottgonzalez** [comment] 2015-11-03 15:30
Well, connecting via USB is very difficult for me; it only works a small fraction of the time, and when it does, the connection doesn't last very long (see #387).

Assuming that your correct, it seems like either the update process is checking something it shouldn't be checking, or the error message is wrong (perhaps a try/catch that's surrounding too much code?).

I'll try again later. I can't connect to the wifi at work because of the way the permissions work.

**Comment by rwaldron** [comment] 2015-11-03 17:02
> Assuming that your correct,

It's a hard requirement. The issues with USB _must_ resolved.

**Comment by johnnyman727** [comment] 2015-11-07 01:37
This is a duplicate of https://github.com/tessel/t2-cli/issues/276.

**Closed by johnnyman727** 2015-11-07 01:37 UTC
