### ISSUE TITLE
t2 provision is broken

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-cli#448] opened 2015-11-15 22:06 UTC
```sh
t2 provision
Unhandled rejection Error: No key provided to set as default.
    at /Users/frijol/t2-cli/lib/tessel/provision.js:160:21
    at Object.actions.setDefaultKey (/Users/frijol/t2-cli/lib/tessel/provision.js:157:10)
    at Function.Tessel.get (/Users/frijol/t2-cli/lib/controller.js:121:20)
    at /Users/frijol/t2-cli/lib/controller.js:280:19
    at tryCatcher (/Users/frijol/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/frijol/t2-cli/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/frijol/t2-cli/node_modules/bluebird/js/main/promise.js:70:37)
    at Object.controller.standardTesselCommand (/Users/frijol/t2-cli/lib/controller.js:278:10)
    at executeProvision (/Users/frijol/t2-cli/lib/controller.js:517:25)
    at tryCatcher (/Users/frijol/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/frijol/t2-cli/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/frijol/t2-cli/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/frijol/t2-cli/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/frijol/t2-cli/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/frijol/t2-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/frijol/t2-cli/node_modules/bluebird/js/main/async.js:15:14)
```

**Comment by rwaldron** [comment] 2015-11-15 23:36
Duplicate of #436

**Closed by rwaldron** 2015-11-15 23:36 UTC
