### ISSUE TITLE
[wifi] Cannot connect over WiFi WPA2-PSK [AES]

### ISSUE THREAD

**Issue by pmcalabrese** [tessel/t2-cli#687] opened 2016-04-17 22:55 UTC
I've a WiFi network protected with  WPA2-PSK [AES] and a Tessel 2 with the firmware 0.12 connected over USB.
I can see the network i want to connect to with `t2 wifi -l`, but when i enter `t2 wifi -n netid -p passid -s psk2` or `t2 wifi -n netid -p passid -s wpa2`  it says

WARN Unable to verify connection. Please ensure you have entered the correct network credentials.

I'm 100% sure the credential are correct. Don't know what to do at this point. Any suggestion is welcome.

**Comment by johnnyman727** [comment] 2016-04-18 02:48
@pmcalabrese are you able to connect to any other networks? Is your password unusual in anyway (in terms of characters or number of words, etc)? Can you see your network when you run `t2 wifi --list`?

**Comment by HipsterBrown** [comment] 2016-04-18 15:17
@pmcalabrese Thank you for making an issue. There are quite a few configuration operations that can be set for wifi secutiy -> [Reference Docs](https://wiki.openwrt.org/doc/uci/wireless#wpa_modes). At the moment, `psk2` should cover your security setting of WPA2-PSK [AES]. 

Can I ask what router you're using? 

Also, have you tried using quotes around your `netid` and/or `passid` just in case there are any odd characters being used?

**Comment by pmcalabrese** [comment] 2016-04-18 17:43
@johnnyman727  @HipsterBrown  yes I can see my network. I've tried both with single and double quote with no success.

I've tried to connect to an iPhone 6 (wifi hotspot) all good. No problem.

My router is a NETGER CG2000.

**Comment by HipsterBrown** [comment] 2016-04-18 18:09
Thanks for the update.

Does your router have any other types of WPA2-PSK security options? i.e. something other than [AES] but still WPA2-PSK. 

Also, is your network using a 5GHz or 2.4GHz frequency? It should tell you in your router's configuration settings under "Channel".

**Comment by pmcalabrese** [comment] 2016-04-19 09:10
It's 2.4 GHz router, I've tried also WPA but still without success,

**Comment by johnnyman727** [comment] 2016-08-09 18:14
I'm closing this issue because it's unclear how to reproduce or fix but if anyone else experiences this problem, please do comment with details.

**Closed by johnnyman727** 2016-08-09 18:14 UTC

**Comment by guozheng** [comment] 2018-06-01 05:30
@pmcalabrese I was having the same issue, later I tried to increase the timeout (default is 5 sec) via `-t` option to 20 sec, then I can connect successfully. You can give it a try.
