### ISSUE TITLE
`t2 key generate` dumps error to file name + .pub

### ISSUE THREAD

**Issue by gyaresu** [tessel/t2-cli#187] opened 2015-07-07 05:18 UTC
## First I cloned [t2-cli](https://github.com/tessel/t2-cli)

```bash
gyaresu@shazbot:~/programming/projects|
⇒  git clone https://github.com/tessel/t2-cli && cd t2-cli
```

## Then I ran `npm link`

```bash
gyaresu@shazbot:~/programming/projects/t2-cli|master
⇒  npm link
npm WARN prefer global grunt-cli@0.1.13 should be installed with -g

> usb@1.0.6 install /Users/gyaresu/programming/projects/t2-cli/node_modules/usb
> node-pre-gyp install --fallback-to-build

[usb] Success: "/Users/gyaresu/programming/projects/t2-cli/node_modules/usb/src/binding/usb_bindings.node" is installed via remote
npm WARN installMany async was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colony-compiler was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colors was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colorsafeconsole was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany debug was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany effess was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany fstream was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany hardware-resolve was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany humanize was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany my-local-ip was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany nomnom was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany structured-clone was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany temp was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany usb was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree

> tessel@0.3.23 postinstall /Users/gyaresu/programming/projects/t2-cli/node_modules/tessel
> tessel install-drivers || true; tessel trademark || true

INFO No driver installation necessary.
TESSEL™ by TECHNICAL MACHINE™
shell-escape@0.2.0 node_modules/shell-escape

keypress@0.2.1 node_modules/keypress

usb-daemon-parser@0.0.1 node_modules/usb-daemon-parser

envfile@1.0.0 node_modules/envfile

sprintf-js@1.0.2 node_modules/sprintf-js

colors@1.1.2 node_modules/colors

async@0.9.2 node_modules/async

bluebird@2.9.32 node_modules/bluebird

ssh-keygen@0.2.1 node_modules/ssh-keygen
└── underscore@1.4.4

mkdirp@0.5.1 node_modules/mkdirp
└── minimist@0.0.8

debug@2.2.0 node_modules/debug
└── ms@0.7.1

fs-extra@0.18.4 node_modules/fs-extra
├── jsonfile@2.2.1
└── graceful-fs@3.0.8

osenv@0.1.3 node_modules/osenv
├── os-tmpdir@1.0.1
└── os-homedir@1.0.0

lodash@3.10.0 node_modules/lodash

nomnom@1.8.1 node_modules/nomnom
├── underscore@1.6.0
└── chalk@0.4.0 (ansi-styles@1.0.0, has-color@0.1.7, strip-ansi@0.1.1)

promzard@0.3.0 node_modules/promzard
└── read@1.0.6 (mute-stream@0.0.5)

grunt-contrib-watch@0.6.1 node_modules/grunt-contrib-watch
├── async@0.2.10
├── lodash@2.4.2
├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
└── gaze@0.5.1 (globule@0.1.0)

mdns-js@0.3.1 node_modules/mdns-js
├── semver@4.3.6
└── mdns-js-packet@0.1.10 (qap@3.1.3)

grunt-cli@0.1.13 node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

sinon@1.15.4 node_modules/sinon
├── formatio@1.1.1
├── samsam@1.1.2
├── lolex@1.1.0
└── util@0.10.3 (inherits@2.0.1)

ssh2@0.4.9 node_modules/ssh2
├── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── ssh2-streams@0.0.14 (streamsearch@0.1.2, jsbn@0.0.0, asn1@0.2.2)

grunt@0.4.5 node_modules/grunt
├── dateformat@1.0.2-1.2.3
├── which@1.0.9
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── colors@0.6.2
├── rimraf@2.2.8
├── async@0.1.22
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── exit@0.1.2
├── nopt@1.0.10 (abbrev@1.0.7)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.6.5)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)
├── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)
└── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)

rimraf@2.4.1 node_modules/rimraf
└── glob@4.5.3 (inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@2.0.8)

grunt-jsbeautifier@0.2.10 node_modules/grunt-jsbeautifier
├── semver@4.3.6
├── underscore.string@3.1.1
├── rc@1.0.3 (ini@1.3.4, strip-json-comments@0.1.3, deep-extend@0.2.11, minimist@0.0.10)
└── js-beautify@1.5.10 (nopt@3.0.3, config-chain@1.1.9)

grunt-contrib-jshint@0.11.2 node_modules/grunt-contrib-jshint
├── hooker@0.2.3
└── jshint@2.8.0 (strip-json-comments@1.0.2, exit@0.1.2, shelljs@0.3.0, console-browserify@1.1.0, cli@0.6.6, minimatch@2.0.8, lodash@3.7.0, htmlparser2@3.8.3)

npm@2.12.1 node_modules/npm

usb@1.0.6 node_modules/usb
└── nan@1.8.4

grunt-jscs@1.8.0 node_modules/grunt-jscs
├── vow@0.4.10
├── hooker@0.2.3
├── lodash@2.4.2
└── jscs@1.13.1 (strip-json-comments@1.0.2, pathval@0.1.1, commander@2.6.0, estraverse@1.9.3, exit@0.1.2, cli-table@0.3.1, minimatch@2.0.8, esprima-harmony-jscs@1.1.0-bin, esprima@1.2.5, xmlbuilder@2.6.4
, glob@5.0.13, chalk@1.0.0, vow-fs@0.3.4, prompt@0.2.14, lodash.assign@3.0.0)

tessel@0.3.23 node_modules/tessel
├── my-local-ip@1.0.0
├── colorsafeconsole@0.0.4
├── debug@0.8.1
├── effess@0.0.5
├── structured-clone@0.2.2
├── colors@0.6.2
├── humanize@0.0.9
├── mkdirp@0.3.5
├── async@0.2.10
├── semver@2.3.2
├── nomnom@1.6.2 (colors@0.5.1, underscore@1.4.4)
├── tar@0.1.20 (inherits@2.0.1, block-stream@0.0.8)
├── temp@0.6.0 (osenv@0.0.3, rimraf@2.1.4)
├── hardware-resolve@0.1.6 (osenv@0.0.3, minimatch@0.2.14)
├── colony-compiler@1.0.1 (async@0.9.2, optimist@0.5.2)
├── fstream@0.1.31 (inherits@2.0.1, graceful-fs@3.0.8, mkdirp@0.5.1)
└── request@2.47.0 (caseless@0.6.0, aws-sign2@0.5.0, forever-agent@0.5.2, oauth-sign@0.4.0, tunnel-agent@0.4.1, stringstream@0.0.4, json-stringify-safe@5.0.1, node-uuid@1.4.3, qs@2.3.3, mime-types@1.0.2,
 tough-cookie@2.0.0, combined-stream@0.0.7, http-signature@0.10.1, hawk@1.1.1, form-data@0.1.4, bl@0.9.4)

grunt-contrib-nodeunit@0.4.1 node_modules/grunt-contrib-nodeunit
├── hooker@0.2.3
└── nodeunit@0.9.1 (tap@0.7.1)
/Users/gyaresu/.node/bin/t2 -> /Users/gyaresu/.node/lib/node_modules/t2-cli/bin/tessel-2.js
/Users/gyaresu/.node/lib/node_modules/t2-cli -> /Users/gyaresu/programming/projects/t2-cli
```

## Then in my working directory I attempted to create the key

```bash
gyaresu@shazbot:~/programming/projects/tessel2-vm|
⇒  t2 key generate
INFO Creating public and private keys for Tessel authentication...
evalmachine.<anonymous>:491
  binding.open(pathModule._makeLong(path),
          ^
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.open (evalmachine.<anonymous>:491:11)
    at OpenReq.process (/Users/gyaresu/programming/projects/t2-cli/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:53:16)
    at OpenReq.Req (/Users/gyaresu/programming/projects/t2-cli/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:124:8)
    at new OpenReq (/Users/gyaresu/programming/projects/t2-cli/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:47:7)
    at Object.open (/Users/gyaresu/programming/projects/t2-cli/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:39:3)
    at fs.writeFile (evalmachine.<anonymous>:1075:6)
    at /Users/gyaresu/programming/projects/t2-cli/node_modules/async/lib/async.js:567:21
    at /Users/gyaresu/programming/projects/t2-cli/node_modules/async/lib/async.js:246:17
    at /Users/gyaresu/programming/projects/t2-cli/node_modules/async/lib/async.js:122:13
    at _each (/Users/gyaresu/programming/projects/t2-cli/node_modules/async/lib/async.js:46:13)
    at async.each (/Users/gyaresu/programming/projects/t2-cli/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/Users/gyaresu/programming/projects/t2-cli/node_modules/async/lib/async.js:245:13)
    at Object.map (/Users/gyaresu/programming/projects/t2-cli/node_modules/async/lib/async.js:216:23)
    at _parallel (/Users/gyaresu/programming/projects/t2-cli/node_modules/async/lib/async.js:565:20)
    at Object.async.parallel (/Users/gyaresu/programming/projects/t2-cli/node_modules/async/lib/async.js:595:9)
```

## Ending up with the error throwing into a weird file name `.pub`

```bash
gyaresu@shazbot:~/programming/projects/tessel2-vm|
⇒  ls -al
total 8
drwxr-xr-x    4 gyaresu  staff   136  6 Jul 22:03 .
drwxr-xr-x  189 gyaresu  staff  6426  6 Jul 21:57 ..
-rw-r--r--    1 gyaresu  staff     0  6 Jul 22:03 function (err) {?      if (err) {?        reject(err);?      } else {?        resolve();?      }?    }.pub
-rw-r--r--    1 gyaresu  staff  3552  6 Jul 21:57 npm-debug.log
```

## Contents of `npm-debug.log`

```bash
gyaresu@shazbot:~/programming/projects/tessel2-vm|
⇒  tail npm-debug.log
25 error npm  v2.12.0
26 error code E404
27 error 404 Not Found: t2-cli
27 error 404
27 error 404 't2-cli' is not in the npm registry.
27 error 404 You should bug the author to publish it (or use the name yourself!)
27 error 404
27 error 404 Note that you can also install from a
27 error 404 tarball, folder, http url, or git url.
28 verbose exit [ 1, true ]
```

## Alias not found?

```bash
gyaresu@shazbot:~/programming/projects/tessel2-vm|
⇒  t2-cli
zsh: command not found: t2-cli
gyaresu@shazbot:~/programming/projects/tessel2-vm|
⇒  t2

command argument is required

Usage: node t2 <command>

command     one of: provision, run, push, erase, list, init, wifi, key, rename
```

**Comment by johnnyman727** [comment] 2015-07-07 05:28
@gyaresu thanks for finding this! We changed how provisioning works recently and neglected to test key generation. Could you give this branch a try?

**Comment by gyaresu** [comment] 2015-07-07 05:59
Thanks @johnnyman727 

So a couple of things. 
 - It errors but then finishes installing
 - The cert files are created in `~/.tessel/` but shouldn't that be explicit and local rather than defaulting to dotfiles?
 - Weird function file name still gets created. 

Thanks in advance :+1: 

```bash
gyaresu@shazbot:~/programming/projects/t2-cli|jon-fix-key-gen
⇒  git branch
* jon-fix-key-gen
  master
gyaresu@shazbot:~/programming/projects/t2-cli|jon-fix-key-gen
⇒  npm link
npm WARN package.json Dependency 'mkdirp' exists in both dependencies and devDependencies, using 'mkdirp@^0.5.1' from dependencies
npm WARN package.json Dependency 'rimraf' exists in both dependencies and devDependencies, using 'rimraf@^2.4.0' from dependencies
npm WARN package.json Dependency 'sinon' exists in both dependencies and devDependencies, using 'sinon@^1.14.1' from dependencies
npm WARN installMany async was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colony-compiler was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colors was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany colorsafeconsole was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany debug was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany effess was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany fstream was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany hardware-resolve was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany humanize was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany my-local-ip was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany nomnom was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany structured-clone was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany temp was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN installMany usb was bundled with tessel@0.3.23, but bundled package wasn't found in unpacked tree
npm WARN prefer global grunt-cli@0.1.13 should be installed with -g

> tessel@0.3.23 postinstall /Users/gyaresu/programming/projects/t2-cli/node_modules/tessel
> tessel install-drivers || true; tessel trademark || true

module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/gyaresu/programming/projects/t2-cli/node_modules/usb/src/binding/usb_bindings.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/gyaresu/programming/projects/t2-cli/node_modules/usb/usb.js:5:38)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
TESSEL™ by TECHNICAL MACHINE™

> usb@1.0.6 install /Users/gyaresu/programming/projects/t2-cli/node_modules/usb
> node-pre-gyp install --fallback-to-build
...
```

```bash
gyaresu@shazbot:~/programming/projects/tessel2-vm|
⇒  t2 key generate
INFO Creating public and private keys for Tessel authentication...
INFO SSH Keys written.
gyaresu@shazbot:~/programming/projects/tessel2-vm|
⇒  ls
function (err) {?      if (err) {?        reject(err);?      } else {?        resolve();?      }?    }.pub
gyaresu@shazbot:~/programming/projects/tessel2-vm|
⇒  ls -al ~/.tessel
total 16
drwxr-xr-x    4 gyaresu  staff   136  6 Jul 22:55 .
drwxr-xr-x+ 222 gyaresu  staff  7548  6 Jul 22:56 ..
-rw-r--r--    1 gyaresu  staff  1675  6 Jul 22:55 id_rsa
-rw-r--r--    1 gyaresu  staff   382  6 Jul 22:55 id_rsa.pub
gyaresu@shazbot:~/programming/projects/tessel2-vm|
```

**Comment by johnnyman727** [comment] 2015-07-17 05:44
> It errors but then finishes installing

Yes, that should go away once we eliminate dependencies on Tessel 1 CLI. They shouldn't affect anything but they certainly are worrying.

> The cert files are created in ~/.tessel/ but shouldn't that be explicit and local rather than defaulting to dotfiles?

The CLI needs to know exactly where to look for the SSH keys so they can't be placed wherever the command is run. We could potentially create them in the CLI repo but I think it's more idiomatic to put them in a dot file. Another thing we could do is add an option for specifying the path (```-i ./```)

> Weird function file name still gets created.

I can't reproduce this - are you sure it wasn't left over from the last time you ran it?

**Comment by johnnyman727** [comment] 2015-08-18 05:41
Closing until this is reproducible.

**Closed by johnnyman727** 2015-08-18 05:41 UTC
Labels: bug
