### ISSUE TITLE
Unhandled rejection during update

### ISSUE THREAD

**Issue by LinusU** [tessel/t2-cli#276] opened 2015-09-02 16:25 UTC
I got this error when trying to upgrade my t2. At the time it just had the white power led on. I just let it sit for a moment and than the orange and blue led started shining and it seems like the tessel is up and running again. Running `t2 list` only shows it on `LAN` thought, no `USB`. The process never terminated so eventually I just killed it.

```text
INFO Connecting to Tessel...
INFO Connected to Tessel-02A3DB18BE3D over LAN
INFO Updating Tessel-02A3DB18BE3D to latest version (0.0.3)...
INFO Beginning update download. This could take a couple minutes..
INFO Download complete!
INFO Updating OpenWRT (1/2)
INFO Transferring image of size 19.92 MB
INFO Starting OpenWRT update. Please do not remove power from Tessel.
INFO Updating firwmare (2/2)
Unhandled rejection Error: No device found in bootloader mode
    at /Users/linus/coding/t2-cli/lib/usb_connection.js:269:19
    at tryCatcher (/Users/linus/coding/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/linus/coding/t2-cli/node_modules/bluebird/js/main/promise.js:476:31)
    at new Promise (/Users/linus/coding/t2-cli/node_modules/bluebird/js/main/promise.js:69:37)
    at USB.Connection._findBootedDeviceBySerialNumber (/Users/linus/coding/t2-cli/lib/usb_connection.js:255:10)
    at retry [as _onTimeout] (/Users/linus/coding/t2-cli/lib/usb_connection.js:232:19)
    at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by LinusU** [comment] 2015-09-02 16:27
Rebooting the tessel brought it up again as both `USB` and `LAN` in `t2 list`

**Comment by LinusU** [comment] 2015-09-02 16:31
Same issue when trying again (had to use `--force` since it believes that it is at `0.0.3`)

**Comment by johnnyman727** [comment] 2015-09-04 06:42
Fascinating - somehow it didn't make it into bootloader mode. I hadn't seen this one before.

Also, there appears to be a typo `firwmare (2/2)` :(

**Comment by flaki** [comment] 2015-09-05 04:43
Same issue here:
```
flaki@FLAKI-VAIO:~/gh/t2-cli$ t2 update -f
INFO Connecting to Tessel...
INFO Connected to flaki-t2 over LAN
INFO Updating flaki-t2 to latest version (0.0.3)...
INFO Beginning update download. This could take a couple minutes..
INFO Download complete!
INFO Updating OpenWRT (1/2)
INFO Transferring image of size 19.92 MB
INFO Starting OpenWRT update. Please do not remove power from Tessel.
INFO Updating firwmare (2/2)
Unhandled rejection Error: No device found in bootloader mode
    at /home/flaki/gh/t2-cli/lib/usb_connection.js:269:19
    at tryCatcher (/home/flaki/gh/t2-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/home/flaki/gh/t2-cli/node_modules/bluebird/js/main/promise.js:476:31)
    at new Promise (/home/flaki/gh/t2-cli/node_modules/bluebird/js/main/promise.js:69:37)
    at USB.Connection._findBootedDeviceBySerialNumber (/home/flaki/gh/t2-cli/lib/usb_connection.js:255:10)
    at retry [as _onTimeout] (/home/flaki/gh/t2-cli/lib/usb_connection.js:232:19)
    at Timer.listOnTimeout (timers.js:119:15)
```

It's also interesting, since the update seemingly have de-provisioned the device:
```
laki@FLAKI-VAIO:~$ ssh root@flaki-t2.local -i ~/.tessel/id_rsa
ssh: Could not resolve hostname flaki-t2.local: Name or service not known
flaki@FLAKI-VAIO:~$ t2 list
INFO Searching for nearby Tessels...
	Tessel-02A31D7F7BBE	USB	
	Tessel-02A31D7F7BBE	LAN	
```
...but have left the `/app/` directory intact (last pushed app still starts on boot):
```
flaki@FLAKI-VAIO:~$ dterm /dev/ttyACM0
BusyBox v1.23.2 (2015-08-18 06:28:00 UTC) built-in shell (ash)

Tessel 2  /  Built on OpenWrt
root@Tessel-02A31D7F7BBE:/# ls
app      dev      lib      overlay  rom      sbin     tmp      var
bin      etc      mnt      proc     root     sys      usr      www
root@Tessel-02A31D7F7BBE:/# cd app
root@Tessel-02A31D7F7BBE:/app# ls
node_modules  oled.js       ots.js        package.json  start
```

**Comment by johnnyman727** [comment] 2015-09-05 22:48
@flaki are you able to reproduce this? I wonder if this is just a symptom of the first update?

The name reset is a known issue: https://github.com/tessel/t2-cli/issues/252

**Comment by LinusU** [comment] 2015-09-07 16:23
@johnnyman727 This happens to me even when updating from `0.0.3` to `0.0.3` (`--force`)...

**Comment by johnnyman727** [comment] 2015-09-07 17:29
@LinusU can you print out the `list` variable here? https://github.com/tessel/t2-cli/blob/master/lib/usb_connection.js#L257

It looks like it's not going into bootloader mode after being given the command to do so.

My guess is that the logic implemented here to give the co-processor time to go into bootloader mode isn't actually working properly. As in, it should be retrying every 250ms (which is ample time I would think) but instead it tries once and if it fails, it just rejects.

**Comment by LinusU** [comment] 2015-09-07 17:50
@johnnyman727 Very long output, here it is: https://gist.github.com/LinusU/93cf9fb198b2a52fe2b3

I've added the `console.log` as such:

```diff
diff --git a/lib/usb_connection.js b/lib/usb_connection.js
index dd56601..ff583ab 100644
--- a/lib/usb_connection.js
+++ b/lib/usb_connection.js
@@ -255,6 +255,8 @@ USB.Connection.prototype._findBootedDeviceBySerialNumber = function(serialNumber
   return new Promise(function(resolve, reject) {
     // Fetch all attached USB devices
     var list = usb.getDeviceList();
+    console.log('LIST LIST LIST LIST LIST LIST LIST')
+    console.log(list)
 
     for (var i = 0; i < list.length; i++) {
       var device = list[i];
```

**Comment by flaki** [comment] 2016-02-17 23:16
I haven't checked, but seems the same issue.
The device wasn't de-provisioned, per se, though: it lost its name, like the above one, but apart from that everything else remained intact (including configuration, saved wifi, and the app pushed on it, which launched after restart without issue).

Also I can confirm that I didn't see the device didn't enter bootloader mode.

**Comment by johnnyman727** [comment] 2016-04-21 02:15
Closing for now because I haven't seen this in a long time.

**Closed by johnnyman727** 2016-04-21 02:15 UTC
