### ISSUE TITLE
version - TypeError Cannot read ... undefined

### ISSUE THREAD

**Issue by Student007** [tessel/t2-cli#422] opened 2015-10-27 20:32 UTC
Before update I got `undefined` when calling `t2 version` - after I get this:
> t2 version
INFO Looking for your Tessel...
/Users/{anonym}/.nvm/versions/node/v4.2.1/lib/node_modules/t2-cli/node_modules/usb/usb.js:157
	this.interfaceNumber = this.descriptor.bInterfaceNumber
-------------------------------------------^

> TypeError: Cannot read property 'bInterfaceNumber' of undefined
    at Interface.__refresh (/Users/{anonym}/.nvm/versions/node/v4.2.1/lib/node_modules/t2-cli/node_modules/usb/usb.js:157:40)
    at Device.<anonymous> (/Users/{anonym}/.nvm/versions/node/v4.2.1/lib/node_modules/t2-cli/node_modules/usb/usb.js:223:9)

**Comment by Student007** [comment] 2015-10-27 20:37
looks like it is shortly after updating. I saw a 
> WARN Detected a Tessel that may be booting.

when trying again `t2 version` now it says 
> INFO Tessel [Tessel-02A38864DB14] version: 0.0.5

but erased my former `t2 rename xyz` setten name.

Think this is still a bug so I flag it.

**Comment by johnnyman727** [comment] 2015-10-28 15:19
> when trying again t2 version now it says

> INFO Tessel [Tessel-02A38864DB14] version: 0.0.5

@Student007 this is the expected behavior. Are you saying it doesn't properly report the version consistently on `0.0.5`?

**Comment by Student007** [comment] 2015-10-28 18:02
@johnnyman727 yes as you know - I simple talked about this, because this was the result for the second try.

But the state (the bug)  before this works well is revealing a task to do. I am not able to dive into this weekdays. Looks like there is a uncovered state within usb.js.

**Comment by johnnyman727** [comment] 2015-10-31 19:12
@Student007 I'm having trouble reproducing this. My Tessel has `0.0.5` firmware and I'm running `t2 version` repeatedly:
```
➜  t2-cli git:(jon-fast-cli) t2 version
INFO Looking for your Tessel...
INFO Connected to Tessel-Test.
INFO Tessel [Tessel-Test] version: 0.0.5
➜  t2-cli git:(jon-fast-cli) t2 version
INFO Looking for your Tessel...
INFO Connected to Tessel-Test.
INFO Tessel [Tessel-Test] version: 0.0.5
➜  t2-cli git:(jon-fast-cli) t2 version
INFO Looking for your Tessel...
INFO Connected to Tessel-Test.
INFO Tessel [Tessel-Test] version: 0.0.5
➜  t2-cli git:(jon-fast-cli) t2 version
INFO Looking for your Tessel...
INFO Connected to Tessel-Test.
INFO Tessel [Tessel-Test] version: 0.0.5
➜  t2-cli git:(jon-fast-cli) t2 version
INFO Looking for your Tessel...
INFO Connected to Tessel-Test.
INFO Tessel [Tessel-Test] version: 0.0.5
➜  t2-cli git:(jon-fast-cli) t2 version
INFO Looking for your Tessel...
INFO Connected to Tessel-Test.
INFO Tessel [Tessel-Test] version: 0.0.5
➜  t2-cli git:(jon-fast-cli) t2 version
INFO Looking for your Tessel...
INFO Connected to Tessel-Test.
INFO Tessel [Tessel-Test] version: 0.0.5
➜  t2-cli git:(jon-fast-cli) t2 version
INFO Looking for your Tessel...
INFO Connected to Tessel-Test.
INFO Tessel [Tessel-Test] version: 0.0.5
➜  t2-cli git:(jon-fast-cli) t2 version
INFO Looking for your Tessel...
INFO Connected to Tessel-Test.
INFO Tessel [Tessel-Test] version: 0.0.5
➜  t2-cli git:(jon-fast-cli) t2 version --lan
INFO Looking for your Tessel...
INFO Connected to Tessel-Test.
INFO Tessel [Tessel-Test] version: 0.0.5
```

Do you have any tips for making this bug reproducible?

**Comment by johnnyman727** [comment] 2015-11-25 20:55
Closing for now because I can't reproduce.

**Closed by johnnyman727** 2015-11-25 20:55 UTC
Labels: bug
