### ISSUE TITLE
NPM Module not fully installed

### ISSUE THREAD

**Issue by ericuldall** [tessel/t2-cli#1015] opened 2016-10-06 02:26 UTC
I've written an npm web server and am trying to run it on my Tessel 2, however the node_modules I've included don't seem to be getting fully installed.

I rooted into my Tessel and dug through the file system and it looked like the following:

```
/app/remote-script/node_modules/express_mvc/lib
    -> lib/ExpressMVC.js
```

There should be many files installed in the lib folder, however only the base file is installed. Is this a known bug with any fixes?

**Comment by ericuldall** [comment] 2016-10-06 02:27
Here's an `ls` inside of /lib:

```
App.js		Dir		ExpressMVC.js	Loader		Log
Config		Exception	Interface	Loader.js	Router.js
```

**Comment by dbuentello** [comment] 2016-10-06 05:13
how are you deploying to the Tessel? `t2 run` or `t2 push`? Are you using any additional arguments? See https://tessel.gitbooks.io/t2-docs/content/API/CLI.html

**Comment by ericuldall** [comment] 2016-10-06 16:56
After some more research it seems to be an issue with the slim builds. However, if I try to run a full build I exhaust all the space on the device. I switched to a very minimal http server implementation and got it working fine now.

For the record the following commands are what I tried with my previous setup:

`t2 run server.js` didn't work, couldn't find file error
`t2 push server.js` pushed the files, when I rooted in the filesystem was missing many files. It seems to only push the files required by the server.js file, but not files required by those files.

**Comment by HipsterBrown** [comment] 2016-10-06 17:37
@ericuldall Are the files missing from the `express_mvc` module? Is it possible to add the missing files to the [`.tesselinclude`](https://tessel.gitbooks.io/t2-docs/content/API/CLI.html#project-files)?

**Comment by dbuentello** [comment] 2016-10-06 17:37
Going full build does guarantee file inclusion but, as in your situation, its very easy to exhaust space. 

A better approach would be to use `.tesselignore ` and `.tesselinclude ` to selectively include what you need.

**Comment by rwaldron** [comment] 2016-10-06 22:23
>  seems to be an issue with the slim builds

It's not an issue, it's all by design. Slim builds create a dependency graph using [module-deps](https://www.npmjs.com/package/module-deps) (which is used by browserify), to trace dependencies by doing a static analysis of the source code starting with the entry point that you specify in `t2 run <entry>`. Since `express_mvc` does dynamic requires (eg. https://github.com/the-letter-e-production/Express-MVC/blob/npm/lib/ExpressMVC.js#L1), it's impossible to do this static analysis. This can be fixed one of two ways: 

1. `express_mvc` can add a file to its root called `.tesselinclude` that contains globbing expressions that correspond to the files for which inclusion must be ensured. That's probably as simple as: `lib/**/*.js`
2. `express_mvc` can refactor to not use dynamic requires. 


The first one is way easier. I'm going to close this because the report itself is about something that is very much by design and not subject to change. We can reopen for further investigation if that seems necessary.

**Closed by rwaldron** 2016-10-06 22:23 UTC

**Comment by ericuldall** [comment] 2016-10-06 22:50
Yea. I think it's just too much of a headache going down the .tesselinclude rabbit hole on this one. I initially tried that, then started getting errors for missing files in npm moduels that express_mvc uses, namely express.

I decided it was better to embrace the idea of a slim build and go with a basic http server. I'll probably end up releasing a new mvc that is optimized for the Tessel's restrictive space requirements. I appreciate the feedback here, I'm on day 2 of Tesseling, so there is much I don't know. You are all very helpful. TY

**Comment by dbuentello** [comment] 2016-10-07 02:09
@ericuldall you should check out our slack channels. https://tessel-slack.herokuapp.com/

We are always looking for new and unique tessel use cases :)
