### ISSUE TITLE
t2 push stuck after "Deployed."

### ISSUE THREAD

**Issue by andreassolberg** [tessel/t2-cli#1512] opened 2018-08-05 07:06 UTC
When I push an app, even if it is the simple blinky app, it always hangs after the Deployed. line:

```
$ t2 push index.js
INFO Looking for your Tessel...
INFO Connected to water.
INFO Building project.
INFO Writing project to Flash on water (1027.584 kB)...
INFO Deployed.
\ 
```

with a spinning wheel indicating that it is waiting for something.

It works perfectly to run the apps using `t2 run`.

If I Ctrl+C when it is stuck in Deployed, it does not run. When I type `t2 restart` I actually can make it start! However when I reboot the tessel it does not start again, and when I re-run `t2 restart` after reboot it says `WARN "index.js" not found on water`.

The `/app` folder contains just a `start` script and no other content.

What can I do to debug why it is stuck?

```
$ t2 version
INFO Looking for your Tessel...
INFO Connected to water.
INFO Tessel Environment Versions:
INFO t2-cli: 0.1.19
INFO t2-firmware: 0.2.0
INFO Node.js: 8.11.3
```

**Comment by andreassolberg** [comment] 2018-08-05 07:36
I downgraded t2-cli to 0.1.15, and then it works!

**Comment by HipsterBrown** [comment] 2018-08-08 16:06
@andreassolberg Thanks for creating an issue. If you run your program with `--loglevel debug` that should provide more feedback as to what is happening. 

The program will not restart after Tessel reboots because `t2 run` places the program in the `/tmp` directory on the device, so it is removed when the board powers off. If you run `t2 push` (this will save the program to flash storage), does that work successfully for you?

**Comment by rwaldron** [comment] 2018-08-19 17:27
I can't reproduce this issue:

```
rwaldron in ~/robotz/t2-simple
$ t2 version
INFO Looking for your Tessel...
INFO Connected to maria.
INFO Tessel Environment Versions:
INFO t2-cli: 0.1.19
INFO t2-firmware: 0.2.0
INFO Node.js: 8.11.3
rwaldron in ~/robotz/t2-simple
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to maria.
INFO Building project.
INFO Writing project to RAM on maria (3.072 kB)...
INFO Deployed.
INFO Running index.js...
I'm blinking! (Press CTRL + C to stop)

rwaldron in ~/robotz/t2-simple
$ t2 push index.js
INFO Looking for your Tessel...
INFO Connected to maria.
INFO Building project.
INFO Writing project to Flash on maria (3.072 kB)...
INFO Deployed.
INFO Your Tessel may now be untethered.
INFO The application will run whenever Tessel boots up.
INFO      To remove this application, use "t2 erase".
INFO Running index.js...
rwaldron in ~/robotz/t2-simple
```

**Comment by HipsterBrown** [comment] 2018-10-01 14:53
@unitof Thanks for the debug output. I wonder if @andreassolberg was also running the script over LAN.

**Comment by Frijol** [comment] 2018-11-02 00:08
oh I had this issue as well! I was running over LAN

**Comment by HipsterBrown** [comment] 2018-11-09 01:05
@Bijesse Thanks for the update. Will probably try reproducing this again this weekend.

**Comment by m-pabon** [comment] 2018-12-05 02:42
I am running into the same issue except it works for me on USB exclusively. The `t2 push` command does not work if I specify the `--lan` flag. I am working with the simple led blinking script generated after a `t2 init` command. Just figured I'd provide an update.

**Comment by HipsterBrown** [comment] 2018-12-05 16:23
@m-pabon We have fix in the works now. https://github.com/tessel/t2-cli/pull/1579 Should be merged and deployed this week.

**Comment by pdillon** [comment] 2018-12-16 15:44
Fix looks good - was able to push after upgrading the cli and `t2 reboot`. Thanks!

**Comment by HipsterBrown** [comment] 2018-12-18 18:11
Closing as the latest release of `t2-cli` fixes this issue.

**Closed by HipsterBrown** 2018-12-18 18:11 UTC

**Comment by Frijol** [comment] 2018-12-18 18:57
Thanks so much for this!
