### ISSUE TITLE
board requires reboot after quitting a process with ctrl-c

### ISSUE THREAD

**Issue by ultralame** [tessel/t2-cli#324] opened 2015-09-18 03:28 UTC
when i try to run my code again 
```
INFO Looking for your Tessel...
WARN No Tessels Found.
```
resolved by rebooting board

**Comment by rwaldron** [comment] 2015-09-18 03:31
Todo: confirm that this reproducible with the latest cli and firmware

**Comment by johnnyman727** [comment] 2015-09-18 03:58
Confirmed with my personal Tessel.

**Comment by johnnyman727** [comment] 2015-09-18 04:10
`git bisect` did not find the culprit :/

**Comment by rwaldron** [comment] 2015-09-18 18:37
Interesting. I can't reproduce

**Comment by johnnyman727** [comment] 2015-09-22 05:51
@rwaldron are you on `0.0.4`?

**Comment by rwaldron** [comment] 2015-09-22 19:45
@johnnyman727 I'm always on latest-master

**Comment by johnnyman727** [comment] 2015-09-29 06:01
Fixed with #339.

**Closed by johnnyman727** 2015-09-29 06:01 UTC
