### ISSUE TITLE
Invalid state returned by LED

### ISSUE THREAD

**Issue by goliatone** [tessel/t2-cli#283] opened 2015-09-07 15:33 UTC
```
INFO Connecting to Tessel...
INFO Connected to tes over LAN
INFO Writing index.js to RAM on tes (3.072 kB)...
INFO Deployed.
INFO Running index.js...
I'm blinking! (Press CTRL + C to stop)
I'm blinking! (Press CTRL + C to stop)
/usr/lib/node/tessel-export.js:765
        throw new Error('Invalid state returned by LED:' + value);
              ^
Error: Invalid state returned by LED:255
    at /usr/lib/node/tessel-export.js:765:15
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
INFO Stopping script...
```

```js
// Import the interface to Tessel hardware
var tessel = require('tessel');

// Set the led pins as outputs with initial states
// Truthy initial state sets the pin high
// Falsy sets it low.
var led1 = tessel.led[0];
var led2 = tessel.led[1];

setInterval(function () {
    console.log("I'm blinking! (Press CTRL + C to stop)");
    // Toggle the led states
    led1.toggle();
    led2.toggle();
}, 100);
```

**Comment by LinusU** [comment] 2015-09-07 16:22
This should be fixed by tessel/t2-firmware#96

**Comment by rwaldron** [comment] 2015-09-07 16:30
@LinusU thanks! I was actually with @goliatone when he filed this

I will review that asap :)

**Comment by rwaldron** [comment] 2015-09-07 16:33
Duplicate of https://github.com/tessel/t2-firmware/issues/95

**Closed by rwaldron** 2015-09-07 16:33 UTC

**Comment by LinusU** [comment] 2015-09-07 16:40
Hehe, yes, I believe that that was just something that wasn't meant to be committed (the `''` part).
